title: å¾å©§å | Jinghua Xu
logo: "/images/logo.png?raw=true" 
description: I study&do NLP, recently most interested in Speech processing. June ğŸ™Œ ğŸ³ï¸â€ğŸŒˆ <br>
  
  <br><br>
  <a href="mailto:xujinghua1998@gmail.com">Contact</a>
  <br><br>
  <a href="https://github.com/JINHXu/JINHXu.github.io/raw/master/CV.pdf">Download CV</a> 
  <br><br>
  <a href="">@Jinghua Xu on Twitter</a> 
  <br><br>
  <a href="https://www.kaggle.com/xujinghua">@xujinghua on Kaggle</a>
  <br><br>
  <a href="https://www.linkedin.com/in/jinghua-xu-5509711ab/">View my LinkedIn Profile</a>  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # Google Analytics tracking ID here
